[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "python-telegram-bot[job-queue]>=20.8",
    "requests>=2.32.4",
]
